### ISSUE TITLE
TabCollapse does not preserve active tab on resizing

### ISSUE THREAD

**Issue by nikitul** [flatlogic/bootstrap-tabcollapse#19]
Please do these steps:
1. Open your example (default tab is Profile)
2. Resize window to collapse into accordion mode
3. Click on the Home accordion-tab
4. Resize it back to tab mode - and the active tab will be Profile, not Home

Is not a big issue but...
Great job! :)

**Comment by gaykov** [comment]
Thanks @nikitul. Fixed now:)

**Comment by nikitul** [comment]
Thank you too :)

**Comment by MarcelJurtz** [comment]
Sorry to open up this old issue - but I have this problem still occurring. This is reproducable in the demo linked in README.md
